import { FestaHeldItem, Pokemon } from './pokemon.model';

const FIXED_FORM_ITEMS: Record<string, [id: string, name: string]> = {
  venusaurmega: ['venusaurite', 'Venusaurite'],
  charizardmegax: ['charizarditex', 'Charizardite X'],
  charizardmegay: ['charizarditey', 'Charizardite Y'],
  blastoisemega: ['blastoisinite', 'Blastoisinite'],
  beedrillmega: ['beedrillite', 'Beedrillite'],
  pidgeotmega: ['pidgeotite', 'Pidgeotite'],
  raichumegax: ['raichunitex', 'Raichunite X'],
  raichumegay: ['raichunitey', 'Raichunite Y'],
  clefablemega: ['clefablite', 'Clefablite'],
  alakazammega: ['alakazite', 'Alakazite'],
  victreebelmega: ['victreebelite', 'Victreebelite'],
  slowbromega: ['slowbronite', 'Slowbronite'],
  gengarmega: ['gengarite', 'Gengarite'],
  kangaskhanmega: ['kangaskhanite', 'Kangaskhanite'],
  starmiemega: ['starminite', 'Starminite'],
  pinsirmega: ['pinsirite', 'Pinsirite'],
  gyaradosmega: ['gyaradosite', 'Gyaradosite'],
  aerodactylmega: ['aerodactylite', 'Aerodactylite'],
  dragonitemega: ['dragoninite', 'Dragoninite'],
  mewtwomegax: ['mewtwonitex', 'Mewtwonite X'],
  mewtwomegay: ['mewtwonitey', 'Mewtwonite Y'],
  meganiummega: ['meganiumite', 'Meganiumite'],
  feraligatrmega: ['feraligite', 'Feraligite'],
  ampharosmega: ['ampharosite', 'Ampharosite'],
  steelixmega: ['steelixite', 'Steelixite'],
  scizormega: ['scizorite', 'Scizorite'],
  heracrossmega: ['heracronite', 'Heracronite'],
  skarmorymega: ['skarmorite', 'Skarmorite'],
  houndoommega: ['houndoominite', 'Houndoominite'],
  tyranitarmega: ['tyranitarite', 'Tyranitarite'],
  sceptilemega: ['sceptilite', 'Sceptilite'],
  blazikenmega: ['blazikenite', 'Blazikenite'],
  swampertmega: ['swampertite', 'Swampertite'],
  gardevoirmega: ['gardevoirite', 'Gardevoirite'],
  sableyemega: ['sablenite', 'Sablenite'],
  mawilemega: ['mawilite', 'Mawilite'],
  aggronmega: ['aggronite', 'Aggronite'],
  medichammega: ['medichamite', 'Medichamite'],
  manectricmega: ['manectite', 'Manectite'],
  sharpedomega: ['sharpedonite', 'Sharpedonite'],
  cameruptmega: ['cameruptite', 'Cameruptite'],
  altariamega: ['altarianite', 'Altarianite'],
  banettemega: ['banettite', 'Banettite'],
  chimechomega: ['chimechite', 'Chimechite'],
  absolmega: ['absolite', 'Absolite'],
  absolmegaz: ['absolitez', 'Absolite Z'],
  glaliemega: ['glalitite', 'Glalitite'],
  salamencemega: ['salamencite', 'Salamencite'],
  metagrossmega: ['metagrossite', 'Metagrossite'],
  latiasmega: ['latiasite', 'Latiasite'],
  latiosmega: ['latiosite', 'Latiosite'],
  kyogreprimal: ['blueorb', 'Blue Orb'],
  groudonprimal: ['redorb', 'Red Orb'],
  staraptormega: ['staraptite', 'Staraptite'],
  lopunnymega: ['lopunnite', 'Lopunnite'],
  garchompmega: ['garchompite', 'Garchompite'],
  garchompmegaz: ['garchompitez', 'Garchompite Z'],
  lucariomega: ['lucarionite', 'Lucarionite'],
  lucariomegaz: ['lucarionitez', 'Lucarionite Z'],
  abomasnowmega: ['abomasite', 'Abomasite'],
  gallademega: ['galladite', 'Galladite'],
  froslassmega: ['froslassite', 'Froslassite'],
  dialgaorigin: ['adamantcrystal', 'Adamant Crystal'],
  palkiaorigin: ['lustrousglobe', 'Lustrous Globe'],
  heatranmega: ['heatranite', 'Heatranite'],
  giratinaorigin: ['griseouscore', 'Griseous Core'],
  darkraimega: ['darkranite', 'Darkranite'],
  arceusbug: ['insectplate', 'Insect Plate'],
  arceusdark: ['dreadplate', 'Dread Plate'],
  arceusdragon: ['dracoplate', 'Draco Plate'],
  arceuselectric: ['zapplate', 'Zap Plate'],
  arceusfairy: ['pixieplate', 'Pixie Plate'],
  arceusfighting: ['fistplate', 'Fist Plate'],
  arceusfire: ['flameplate', 'Flame Plate'],
  arceusflying: ['skyplate', 'Sky Plate'],
  arceusghost: ['spookyplate', 'Spooky Plate'],
  arceusgrass: ['meadowplate', 'Meadow Plate'],
  arceusground: ['earthplate', 'Earth Plate'],
  arceusice: ['icicleplate', 'Icicle Plate'],
  arceuspoison: ['toxicplate', 'Toxic Plate'],
  arceuspsychic: ['mindplate', 'Mind Plate'],
  arceusrock: ['stoneplate', 'Stone Plate'],
  arceussteel: ['ironplate', 'Iron Plate'],
  arceuswater: ['splashplate', 'Splash Plate'],
  emboarmega: ['emboarite', 'Emboarite'],
  excadrillmega: ['excadrite', 'Excadrite'],
  audinomega: ['audinite', 'Audinite'],
  scolipedemega: ['scolipite', 'Scolipite'],
  scraftymega: ['scraftinite', 'Scraftinite'],
  eelektrossmega: ['eelektrossite', 'Eelektrossite'],
  chandeluremega: ['chandelurite', 'Chandelurite'],
  golurkmega: ['golurkite', 'Golurkite'],
  genesectdouse: ['dousedrive', 'Douse Drive'],
  genesectshock: ['shockdrive', 'Shock Drive'],
  genesectburn: ['burndrive', 'Burn Drive'],
  genesectchill: ['chilldrive', 'Chill Drive'],
  chesnaughtmega: ['chesnaughtite', 'Chesnaughtite'],
  delphoxmega: ['delphoxite', 'Delphoxite'],
  greninjamega: ['greninjite', 'Greninjite'],
  pyroarmega: ['pyroarite', 'Pyroarite'],
  floettemega: ['floettite', 'Floettite'],
  meowsticmmega: ['meowsticite', 'Meowsticite'],
  meowsticmalemega: ['meowsticite', 'Meowsticite'],
  meowsticfmega: ['meowsticite', 'Meowsticite'],
  meowsticfemalemega: ['meowsticite', 'Meowsticite'],
  malamarmega: ['malamarite', 'Malamarite'],
  barbaraclemega: ['barbaracite', 'Barbaracite'],
  dragalgemega: ['dragalgite', 'Dragalgite'],
  hawluchamega: ['hawluchanite', 'Hawluchanite'],
  zygardemega: ['zygardite', 'Zygardite'],
  dianciemega: ['diancite', 'Diancite'],
  crabominablemega: ['crabominite', 'Crabominite'],
  golisopodmega: ['golisopite', 'Golisopite'],
  silvallybug: ['bugmemory', 'Bug Memory'],
  silvallydark: ['darkmemory', 'Dark Memory'],
  silvallydragon: ['dragonmemory', 'Dragon Memory'],
  silvallyelectric: ['electricmemory', 'Electric Memory'],
  silvallyfairy: ['fairymemory', 'Fairy Memory'],
  silvallyfighting: ['fightingmemory', 'Fighting Memory'],
  silvallyfire: ['firememory', 'Fire Memory'],
  silvallyflying: ['flyingmemory', 'Flying Memory'],
  silvallyghost: ['ghostmemory', 'Ghost Memory'],
  silvallygrass: ['grassmemory', 'Grass Memory'],
  silvallyground: ['groundmemory', 'Ground Memory'],
  silvallyice: ['icememory', 'Ice Memory'],
  silvallypoison: ['poisonmemory', 'Poison Memory'],
  silvallypsychic: ['psychicmemory', 'Psychic Memory'],
  silvallyrock: ['rockmemory', 'Rock Memory'],
  silvallysteel: ['steelmemory', 'Steel Memory'],
  silvallywater: ['watermemory', 'Water Memory'],
  drampamega: ['drampanite', 'Drampanite'],
  necrozmaultra: ['ultranecroziumz', 'Ultranecrozium Z'],
  magearnamega: ['magearnite', 'Magearnite'],
  magearnaoriginalmega: ['magearnite', 'Magearnite'],
  zeraoramega: ['zeraorite', 'Zeraorite'],
  falinksmega: ['falinksite', 'Falinksite'],
  zaciancrowned: ['rustedsword', 'Rusted Sword'],
  zamazentacrowned: ['rustedshield', 'Rusted Shield'],
  scovillainmega: ['scovillainite', 'Scovillainite'],
  glimmoramega: ['glimmoranite', 'Glimmoranite'],
  tatsugiricurlymega: ['tatsugirinite', 'Tatsugirinite'],
  tatsugiridroopymega: ['tatsugirinite', 'Tatsugirinite'],
  tatsugiristretchymega: ['tatsugirinite', 'Tatsugirinite'],
  baxcaliburmega: ['baxcalibrite', 'Baxcalibrite'],
  ogerponwellspring: ['wellspringmask', 'Wellspring Mask'],
  ogerponwellspringmask: ['wellspringmask', 'Wellspring Mask'],
  ogerponhearthflame: ['hearthflamemask', 'Hearthflame Mask'],
  ogerponhearthflamemask: ['hearthflamemask', 'Hearthflame Mask'],
  ogerponcornerstone: ['cornerstonemask', 'Cornerstone Mask'],
  ogerponcornerstonemask: ['cornerstonemask', 'Cornerstone Mask'],
  ogerponwellspringtera: ['wellspringmask', 'Wellspring Mask'],
  ogerponhearthflametera: ['hearthflamemask', 'Hearthflame Mask'],
  ogerponcornerstonetera: ['cornerstonemask', 'Cornerstone Mask'],
  crucibellemega: ['crucibellite', 'Crucibellite'],
  venomiconepilogue: ['vilevial', 'Vile Vial'],
};

export function fixedFormItem(pokemon: Pokemon): FestaHeldItem | undefined {
  const item = FIXED_FORM_ITEMS[toId(pokemon.rawName ?? pokemon.name)];
  return item ? { id: item[0], name: item[1] } : undefined;
}

export function withFixedFormItem(pokemon: Pokemon): Pokemon {
  if (pokemon.heldItem) return pokemon;
  const heldItem = fixedFormItem(pokemon);
  return heldItem ? { ...pokemon, heldItem } : pokemon;
}

function toId(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '');
}
