import { DOCUMENT } from '@angular/common';
import { Injectable, inject, signal } from '@angular/core';

const en = {
  info: 'Info',
  infoAboutTitle: 'A project by dade',
  infoAboutDescription: 'Pokefunny brings together Pokémon games: build teams in Ten Pick, play with friends online and grow your collection in PokeGacha.',
  infoEmail: 'Contact email',
  infoWebsite: 'Main website',
  infoUpdatesTitle: 'What’s new?',
  infoUpdatesDescription: 'See the latest additions, improvements and fixes.',
  infoOpenChangelog: 'Open changelog',
  changelogBack: 'Back to Info',
  changelogDescription: 'The latest changes to Pokefunny, with the newest updates first.',
  changelogInfo: 'Added Info with contact details, a link to dade.es and this changelog.',
  changelogGachaOpening: 'Animated capsule openings, optional sound and badges for new Pokémon and shinies.',
  changelogGachaPc: 'PC search, sorting, favorites, nicknames and box names. Move Pokémon between boxes and undo releases.',
  changelogGachaDex: 'Search the Pokédex by name or number, filter by type or collection status and view forms and shinies.',
  changelogGachaQuests: 'Collection quests with unlockable rewards and a redesigned progress board.',
  changelogGachaProfile: 'Trainer titles, sound and appearance settings are now together in PC → Profile.',
  changelogGachaBackgrounds: 'Unlocked backgrounds apply across the website. The starry sky now uses a regular star pattern, with light and dark colors.',
  changelogGachaDraws: 'Hourly draws accumulate while you are away, up to three.',
  changelogOnlineEnglish: 'Online play is now available in English and Spanish.',
  changelogOnlineQueue: 'The team list rotates with each turn: the current trainer appears first, followed by the next trainers.',
  changelogOnlineRooms: 'Join games by room code, leave a game and manage rooms from the host screen.',
  changelogOnlineTeams: 'Player phones show all final teams. Trainers also display their favorite Pokémon.',
  changelogOnlineAnimations: 'Improved host layout, animated picks and nickname stickers.',
  changelogFestaShared: 'Shared FESTA draws, abilities and turn results stay synchronized between the host and players.',
  changelogFestaChoices: 'The host displays rival selection and searchable FESTA choices.',
  changelogFestaSkips: 'FESTA card chance is checked after every skipped encounter in online play.',
  gachaProfile: "Profile",
  gachaPcSections: "PC sections",
  gachaAudio: "Sound",
  gachaOpeningSounds: "Opening sounds",
  gachaOpenProfile: "PC · Profile",
  gachaProfileUnlockHint: "Complete quests to unlock more options.",
  gachaEquipProfileHint: "Choose your unlocked rewards in PC · Profile.",
  gachaQuestBoard: "Trainer notice board",
  gachaQuestArchiveHint: "Every capture counts, even after a Pokémon leaves your PC.",
  gachaQuestWaterTitle: "Water team",
  gachaQuestStartersTitle: "The first trio",
  gachaQuestSpeciesTitle: "The collection grows",
  gachaQuestShinyTitle: "A special sparkle",
  gachaQuestKantoTitle: "A walk through Kanto",

  gachaCelebrationFirstShiny: 'Your first shiny! I knew I was hiding a star in here!',
  gachaCelebrationFive: 'Five different Pokémon! This collection is starting to look good!',
  gachaCelebrationTwentyFive: 'Twenty-five! You have earned your place among collectors!',
  gachaNewEntry: "New in your Pokédex!",
  gachaDrawBank: "{count} / 3 draws ready",
  gachaBankFull: "Draw bank full. Open a draw to make room.",
  gachaBankRefill: "Next charge in {time} · one per hour",
  gachaSoundOn: "Sound on",
  gachaSoundOff: "Sound off",
  gachaSearchCollection: "Search name or number",
  gachaType: "Type",
  gachaAllTypes: "All types",
  gachaSort: "Sort by",
  gachaSortSlot: "Box position",
  gachaSortNumber: "Pokédex number",
  gachaSortName: "Name",
  gachaSortRecent: "Most recent",
  gachaFavorites: "Favorites first",
  gachaFavoritesOnly: "Favorites only",
  gachaFavorite: "♥ Mark as favorite",
  gachaUnfavorite: "Remove favorite",
  gachaRenameBox: "Box name",
  gachaUndoRelease: "Undo release (30 s)",
  gachaRestored: "Pokémon returned to the PC.",
  gachaDragHint: "Drag Pokémon between slots or onto another box. On touch screens, use Move.",
  gachaEmptySearch: "No Pokémon match these filters.",
  gachaCollectionSummary: "{count} collected · {shiny} shiny",
  gachaDexCategory: "Collection category",
  gachaSpecies: "Species",
  gachaForms: "Forms",
  gachaAllGenerations: "All generations",
  gachaDexStatus: "Collection status",
  gachaAll: "All",
  gachaOwned: "Captured",
  gachaSeen: "Seen",
  gachaMissing: "Not captured",
  gachaDiscoverHint: "Reveal this Pokémon in a draw to discover its details.",
  gachaShinyOwned: "Shiny registered",
  gachaCloseDetails: "Close details",
  gachaQuests: "Collection quests",
  gachaQuestsHint: "Complete your collection to unlock decorations. Captures still count after releasing a Pokémon.",
  gachaQuestWater: "Capture 5 different Water Pokémon",
  gachaQuestStarters: "Collect the three Kanto starters",
  gachaQuestSpecies: "Capture 25 different species",
  gachaQuestShiny: "Capture your first shiny",
  gachaQuestKanto: "Complete 25% of the Kanto Pokédex",
  gachaReward: "Reward",
  gachaClaimReward: "Claim reward",
  gachaClaimed: "Claimed",
  gachaQuestClaimed: "Unlocked: {reward}",
  gachaCustomize: "Make it yours",
  gachaCustomizeHint: "Choose an unlocked decoration, box background or trainer title.",
  gachaScene: "Page background",
  gachaBoxTheme: "Box background",
  gachaTrainerTitle: "Trainer title",
  gachaLocked: "Locked",
  gachaSceneDefault: "Standard background",
  gachaSceneForest: "Forest corner",
  gachaSceneStars: "Starry sky",
  gachaBoxDefault: "Classic boxes",
  gachaBoxSunset: "Sunset",
  gachaTitleTrainer: "Pokémon Trainer",
  gachaTitleCollector: "Kanto Collector",
  gachaTitleShiny: "Shiny Hunter",
  gachaMachineGrowing: "Your collection is growing! Ready for three more surprises?",
  gachaMachineCollector: "You are becoming quite the collector. Let me see what I have for you...",
  gachaMachineShiny: "I remember that shiny! Shall we look for another?",
  gachaOpening: "The Poké Ball is opening...",

  onlineTurnPrefix: "Turn for",
  onlineSetupHint: "Create a room and share the link. Each player chooses their name when joining; the number of players is decided when you start.",
  onlineCreate: "Create room",
  onlineCreating: "Creating...",
  onlineRoom: "Room",
  onlineLink: "Link",
  onlineDeleteQuestion: "Delete the game for everyone? The room and the game saved on this device will be deleted.",
  onlineDeleting: "Deleting...",
  onlineConfirmDelete: "Yes, delete game",
  onlineDelete: "Delete game",
  onlineLobby: "Lobby · {count} players",
  onlineLobbyHint: "Share the link and start when everyone is ready. Players connected at that moment will participate.",
  onlineConnected: "Connected",
  onlineDisconnected: "Disconnected",
  onlineWaitingPlayers: "Waiting for players...",
  onlineStarting: "Starting...",
  onlineStart: "Start game ({count})",
  onlineViewGame: "View game and create tournament",
  onlineChoosesFor: "chooses the Pokémon for",
  onlineWaitingRival: "Waiting for the rival to choose on their device.",
  onlineResolveDevice: "The active player resolves the card on their device.",
  onlineAdvanceDevice: "The player advances to the next turn on their phone.",
  onlineLeave: "Leave game",
  onlineDeleted: "Game deleted",
  onlineDeletedHint: "The host deleted room {code}. You can create another online game.",
  onlineHome: "Back to home",
  onlineReconnecting: "Reconnecting...",
  onlineRejoin: "Join again",
  onlineWaitingHost: "Waiting for the host...",
  onlineWaitingFor: "Waiting for",
  onlineOtherPlayer: "another player",
  onlineLastEncounter: "Final encounter: you must keep this Pokémon.",
  onlineFestaItem: "FESTA item",
  onlineFestaAbility: "FESTA ability",
  onlineFestaMove: "FESTA move",
  onlineChoosePokemon: "Choose a Pokémon",
  onlineSearchItem: "Search items",
  onlineSearchAbility: "Search abilities",
  onlineSearchMove: "Search moves",
  onlineSearchHint: "Name in Spanish or English",
  onlineSearchResults: "Search results",
  onlineNoResults: "No results. Try another name.",
  onlineSelection: "Selection:",
  onlineRandomItem: "The item will be chosen at random.",
  onlineReroll: "Choose a pick to reroll",
  onlineChangeForm: "Choose a Pokémon to change its form",
  onlineTrade: "Trade",
  onlineTradeLast: "Trade your last pick",
  onlineRivalPokemon: "Rival Pokémon",
  onlineCardError: "Could not prepare the card",
  onlineCardErrorHint: "The server did not send an action to resolve it. Refresh the game; if this continues, the host needs to update the Online server.",
  onlineRefreshing: "Refreshing...",
  onlineRefresh: "Refresh game",
  onlineRecovering: "Recovering your turn",
  onlineNoControls: "Your turn actions have not been received.",
  onlineJoinTitle: "Join a Game",
  onlineRollingRival: "Drawing a rival...",
  onlineRivalChosen: "Rival chosen!",
  onlineRollingFesta: "FESTA draw...",
  onlineFestaResolved: "FESTA card resolved!",
  onlineRolling: "Drawing...",
  onlineResolvedFor: "resolved the card for",
  onlineDrawRival: "Rival chosen",
  onlineDrawPokemon: "Pokémon chosen",
  onlineDrawItem: "Item drawn",
  onlineDrawForm: "Form drawn",
  onlineTimeout: "Could not contact the server. Please wait 1 minute for the server to wake up.",
  onlineUnexpectedError: "Unexpected error.",
  onlineLeft: "You have left the game.",

  playOnline: 'Play Online',
  joinGameHint: 'Enter a room code to join an online game.',
  joinGameButton: 'Join game',
  joinRoomCode: 'Room code',
  joinCodeHint: 'The 6-character code shared by the host.',
  joinPlayerName: 'Name',
  joiningGame: 'Joining...',
  festaZoroarkName: 'It was Zoroark!?',
  festaZoroarkDescription: 'A random Pokemon on your team transforms into Zoroark.',
  festaDittoName: 'It was Ditto!?',
  festaDittoDescription: 'A random Pokemon on your team transforms into Ditto.',
  festaChangeFormName: 'Form Change',
  festaChangeFormDescription: 'Choose one of your Pokemon to change into a random different available form.',
  festaRandomChangeFormName: 'Who is this?',
  festaRandomChangeFormDescription: 'A random eligible Pokemon from any team changes into a different available form.',
  openTournament: 'View tournament',
  competitionRecommendation: 'Recommended format', competitionIdealTitle: 'A great number for a tournament!',
  competitionIdealReason: '{count} players can play single elimination without byes or free qualification.',
  competitionByeReason: 'With {count} players, single elimination needs {byes} direct qualifications.',
  singleElimination: 'Single elimination', swissFormat: 'Swiss system', createCompetition: 'Create tournament',
  createSwiss: 'Create Swiss tournament', useElimination: 'Use single elimination anyway',
  swissDescription: 'Everyone plays several rounds, mainly against players with similar results.',
  eliminationByeNote: 'Some players will qualify for the next round without playing.',
  swissRecommendedRounds: 'Recommendation: {count} Swiss rounds', swissRounds: 'Swiss rounds',
  swissRoundsRange: 'Choose a whole number from 1 to {max}.',
  nearbyTournamentSizes: 'Nearest ideal single-elimination sizes: {lower} and {upper} players.',
  changeCompetitionFormat: 'Change competition format', competitionReplace: 'Creating another tournament will clear the current results.',
  swissRoundProgress: 'Round {current} of {total}', swissNextRound: 'Pair next round', swissCompleted: 'Tournament completed',
  swissBye: 'Bye (+1 point)', swissRematch: 'Rematch: no complete pairing without rematches was possible.',
  swissStandings: 'Standings', swissPoints: 'Points', swissWins: 'Wins', swissLosses: 'Losses', swissByes: 'Byes',
  swissDirect: 'Head-to-head', swissBuchholz: 'Buchholz', swissLottery: 'Draw', swissTrainer: 'Trainer',
  swissScoring: 'Win: 1 point. Loss: 0. Bye: 1 point, without a played win.',
  swissTiebreaks: 'Ties: head-to-head (a complete mini-league for a tied group), then Buchholz (sum of opponents\' points), then the saved random draw. Lower draw number wins.',
  swissUndo: 'Undo last result or pairing', competitionStartError: 'Could not create the competition. Please try again.',
  tournament: 'Tournament', drawTournament: 'Draw tournament', redrawTournament: 'Redraw tournament',
  redrawQuestion: 'Draw again and clear all tournament results?', confirmRedraw: 'Draw again',
  tournamentSummary: '{players} trainers / {matches} battles', tournamentProgress: '{done} / {total} battles completed',
  tournamentBye: 'Direct qualification', tournamentWaiting: 'Awaiting winner', tournamentFinal: 'Final',
  tournamentSemifinals: 'Semifinals', tournamentQuarterfinals: 'Quarterfinals',
  tournamentChampion: 'Champion', tournamentWinner: 'Record {name} as winner', tournamentUndo: 'Undo last result',
  tournamentError: 'Could not save the tournament. Please try again.', closeTeam: 'Close team',
  favoriteQuestion: 'What is your favorite Pokemon?', searchPokemon: 'Search Pokemon',
  changeFavorite: 'Change favorite Pokemon', noPokemonFound: 'No Pokemon found',
  favoriteLoadError: 'Could not load the Pokemon. Please try again.',
  darkMode: 'Enable night mode', lightMode: 'Enable day mode',
  playMonotype: 'Play Ten Pick Monotype', monotypeTagline: 'One type. Six Pokemon.',
  random: 'Random', playerType: 'Type for {name}',
  insufficientPool: 'Not enough eligible Pokemon families for these filters. Create a draft with more generations or a different type.',
  mega: 'Mega', selectGeneration: 'Select at least one generation.',
  generations: 'Generations', specialForms: 'Special forms', gigantamax: 'Gigantamax',
  shiny: 'Shiny',
  home: 'Home', language: 'Language', chooseGame: 'Choose a Pokefunny game',
  tenPickSection: 'Ten Pick games', tenPickHubTagline: 'Draft modes for quick team building.',
  pokeGachaTagline: 'Open capsules and discover Pokemon.', playPokeGacha: 'Play PokeGacha',
  pokeGachaPending: 'Work in progress.',
  alreadyRegistered: 'Already registered in your Pokedex',
  gachaReady: 'Press the machine to draw three Poke Balls.',
  gachaSpinning: 'Spinning...',
  gachaPull: 'Press machine',
  gachaNextDraw: 'Next draw in {time}',
  gachaWaitSorry: 'Sorry! Wait until the next full hour.',
  gachaWaitToldYou: 'I told you that you can\'t.',
  gachaWaitNope: 'Nope.',
  gachaWaitSorryNo: 'Sorry, but no.',
  gachaAnnoyedOffer: '"Fine, pest, I will give you a Poke Ball, but be quiet, okay?"',
  gachaAnnoyedLastOffer: '"Fine, one last Poke Ball. No more after this, okay?"',
  gachaAccept: 'Accept',
  gachaDecline: 'Decline',
  gachaBonusRolling: 'A Poke Ball rolled out from behind the machine.',
  gachaBonusReady: 'Pick up the Poke Ball.',
  gachaBonusPreparing: 'The hidden Poke Ball is shaking...',
  gachaChooseBonus: 'Choose this Pokemon and send it to the PC.',
  gachaChoosePokemon: 'Choose a Pokemon',
  gachaRevealPokemon: 'Reveal Pokemon {count}',
  gachaOpenPc: 'Open PC',
  gachaOpenPokedex: 'Open Pokedex',
  gachaPcPokemon: 'PC Pokemon',
  gachaPokedex: 'Pokedex',
  gachaClose: 'Close',
  gachaBoxes: 'Boxes',
  gachaBox: 'Box {count}',
  gachaSlot: 'Slot {count}',
  gachaNickname: 'Nickname',
  gachaMove: 'Move',
  gachaRelease: 'Release',
  gachaSelectPcPokemon: 'Select a Pokemon from the PC.',
  gachaGeneration: 'Generation {count}',
  gachaRemaining: '{remaining} left out of {total}',
  gachaUnknownPokemon: 'Unknown Pokemon',
  gachaPreparing: 'The machine is preparing the capsules...',
  gachaRevealAll: 'Press each Poke Ball to reveal its Pokemon.',
  gachaLoadError: 'Could not load this draw. Try again.',
  gachaChooseOne: 'Choose one of the three. That Pokemon will go to the PC.',
  gachaKeepRevealing: 'Keep revealing the Poke Balls.',
  gachaRevealFirst: 'Reveal all three Poke Balls first.',
  gachaPcFull: 'The PC is full. Release or move a Pokemon.',
  gachaSavedToPc: '{name} was saved to the PC.',
  gachaChoosePcSlot: 'Choose a PC slot to move it.',
  gachaReleased: '{name} was released. It stays registered in the Pokedex.',
  gachaSaveError: 'Could not save in this browser.',
  tagline: 'Ten encounters. One choice.', play: 'Play Ten Pick', playFesta: 'Play Ten Pick Festa', myDrafts: 'My drafts',
  festaTagline: 'Festa cards can interrupt any encounter.',
  festaChance: 'Festa Card chance (%)', festaResolve: 'Resolve card', festaConfirm: 'Confirm',
  festaDeck: 'Card Deck',
  festaItem: 'Held item', festaMove: 'Move', festaAbility: 'Ability',
  festaAbilityRivalAnyName: 'No Limits for Your Rival: Ability',
  festaAbilityRivalAnyDescription: 'Choose any ability from the list for a randomly selected rival Pokemon.',
  festaAbilityRandomName: 'Surprise Talent',
  festaAbilityRandomDescription: 'Choose any ability from the list for a randomly selected Pokemon from any team.',
  festaAll: 'Everyone', festaRivals: 'Rivals',
  festaInvalidMove: 'This Pokemon cannot learn that move.', festaNoTargets: 'No eligible Pokemon yet.',
  festaItemRandomRivalName: 'A Gift for a Random Rival',
  festaItemRandomRivalDescription: 'Choose an item for a random Pokemon from a rival team.',
  festaItemRandomAllName: 'A Gift for... anyone!?',
  festaItemRandomAllDescription: 'Choose an item for a random Pokemon from any team, including your own.',
  festaItemChosenRivalName: 'A Gift for Your Rival',
  festaItemChosenRivalDescription: 'Choose a rival Pokemon and an item to equip it.',
  festaItemRandomOwnName: 'Surprise Item',
  festaItemRandomOwnDescription: 'A random item is drawn. Choose one of your Pokemon to equip it.',
  festaItemRandomOpponentName: 'Rival Surprise Item',
  festaItemRandomOpponentDescription: 'A random item is drawn. Choose a rival Pokemon to equip it.',
  festaItemChosenRandomName: 'Random Delivery',
  festaItemChosenRandomDescription: 'Choose an item for a random Pokemon on your team.',
  festaItemRandomGroupName: 'Items for Everyone',
  festaItemRandomGroupDescription: 'A random item is drawn. Choose one rival Pokemon to equip it.',
  festaMoveRivalAnyName: 'No Limits for Your Rival',
  festaMoveRivalAnyDescription: 'Write any move for a randomly selected rival Pokemon.',
  festaMoveRandomName: 'Surprise Training',
  festaMoveRandomDescription: 'Write a move for a random Pokemon from any team.',
  festaReroll: 'Reroll', festaReplaced: 'Replaces {name}',
  festaChoosingRival: 'Choosing rival',
  festaRivalSelected: 'Your rival is',
  festaChoosingTarget: 'Choosing Pokemon',
  festaTargetSelected: 'The gift goes to',
  festaRivalChoosesFor: '{rival} chooses for {player}',
  festaFirstPokemon: 'First Pokemon', festaSecondPokemon: 'Second Pokemon', festaYourLastPick: 'Your last pick',
  festaCardFirstStageName: 'First-stage Pokemon',
  festaCardFirstStageDescription: 'Choose a Pokemon that is the first stage of an evolutionary line. It joins your team directly.',
  festaCardMinorLegendaryName: 'Legendary or Mythical',
  festaCardMinorLegendaryDescription: 'Choose a Legendary or Mythical Pokemon. It joins your team directly.',
  festaCardOpponentFullyEvolvedName: 'Rival Fully Evolved',
  festaCardOpponentFullyEvolvedDescription: 'A random rival chooses a fully evolved Pokemon for you. It joins your team directly.',
  festaCardOpponentFirstStageName: 'Rival First-stage Pokemon',
  festaCardOpponentFirstStageDescription: 'A random rival chooses a first-stage Pokemon for you. It joins your team directly.',
  festaCardOpponentMinorLegendaryName: 'Rival Legendary or Mythical',
  festaCardOpponentMinorLegendaryDescription: 'A random rival chooses a Legendary or Mythical Pokemon for you. It joins your team directly.',
  festaCardForcedRerollName: 'Forced Reroll',
  festaCardForcedRerollDescription: 'Replace one of your previous picks with a new Pokemon generated under the normal rules.',
  festaCardTradeAnyName: 'Full Trade',
  festaCardTradeAnyDescription: 'Trade two Pokemon chosen by any two players.',
  festaCardTradeLastName: 'Trade Your Last Pick',
  festaCardTradeLastDescription: 'Swap your most recent Pokemon for another player\'s Pokemon.',
  newDraft: 'New draft', noDrafts: 'No saved drafts', completed: 'Completed', inProgress: 'In progress',
  pokemonPicked: 'Pokemon picked', deleteQuestion: 'Delete this draft?', delete: 'Delete', cancel: 'Cancel',
  viewTeams: 'View teams', continue: 'Continue', deleteDraft: 'Delete draft', deleteDraftFor: 'Delete draft for {name}',
  trainerName: 'Trainer name', add: 'Add', remove: 'Remove', removePlayer: 'Remove {name}',
  draftNicknamesRequired: 'Required nicknames', draftNickname: 'Nickname',
  teamSize: 'Pokemon per team', start: 'Start draft', draftComplete: 'Draft complete', finalTeams: 'Final teams',
  player: 'Player', loading: 'Finding Pokemon...', turnError: 'Could not prepare this turn. Please try again.',
  retry: 'Retry', turnOf: "{name}'s turn", lastEncounter: 'Final encounter', lastChoice: 'This is your last choice',
  pick: 'Pick', skip: 'Skip', remaining: '{count} encounters remaining', teams: 'Teams',
  draftOrder: 'Draft order', round: 'Round {count}', pickedBy: '{name} picked', encounter: 'Encounter',
  picked: 'Picked', skipped: 'Skipped', undiscovered: 'Undiscovered', finalTeamsButton: 'View final teams',
  nextTurn: 'Next turn', preparePaste: 'Prepare Pokepaste', preparePasteFor: 'Prepare Pokepaste for {name}',
  abilitiesLoading: 'Looking up abilities...', viewPaste: 'View Pokepaste', teamOf: "{name}'s team",
  closePaste: 'Close Pokepaste', closePasteFor: 'Close Pokepaste for {name}', copyTeam: 'Copy team',
  copied: 'Copied', copy: 'Copy', teamAbilitiesLoading: 'Looking up abilities for {name}',
  pasteError: 'Could not prepare the team. Please try again.',
  copyError: 'Could not copy. You can select the team text instead.',
  unknownForm: 'The form of {name} is not recognized by Showdown.',
  unknownAbility: 'Could not find the ability for {name}.',
} as const;

export type TranslationKey = keyof typeof en;
export type Language = 'en' | 'es';

const es: Record<TranslationKey, string> = {
  info: 'Info',
  infoAboutTitle: 'Un proyecto de dade',
  infoAboutDescription: 'Pokefunny reúne juegos de Pokémon: crea equipos en Ten Pick, juega con amigos online y amplía tu colección en PokeGacha.',
  infoEmail: 'Email de contacto',
  infoWebsite: 'Página principal',
  infoUpdatesTitle: '¿Qué hay de nuevo?',
  infoUpdatesDescription: 'Consulta las últimas novedades, mejoras y correcciones.',
  infoOpenChangelog: 'Abrir changelog',
  changelogBack: 'Volver a Info',
  changelogDescription: 'Los últimos cambios de Pokefunny, empezando por los más recientes.',
  changelogInfo: 'Nuevo apartado Info con contacto, enlace a dade.es y este changelog.',
  changelogGachaOpening: 'Aperturas de cápsulas animadas, sonido opcional e indicadores de Pokémon nuevos y variocolor.',
  changelogGachaPc: 'Búsqueda, ordenación, favoritos, motes y nombres de cajas en el PC. Puedes mover Pokémon entre cajas y deshacer liberaciones.',
  changelogGachaDex: 'Busca en la Pokédex por nombre o número, filtra por tipo o estado de colección y consulta formas y variocolor.',
  changelogGachaQuests: 'Retos de colección con recompensas desbloqueables y un tablón de progreso rediseñado.',
  changelogGachaProfile: 'Títulos de entrenador, sonido y personalización reunidos en PC → Perfil.',
  changelogGachaBackgrounds: 'Los fondos desbloqueados se aplican a toda la web. El cielo estrellado usa un patrón regular de estrellas, con colores para modo claro y oscuro.',
  changelogGachaDraws: 'Las tiradas se acumulan cada hora mientras estás fuera, hasta un máximo de tres.',
  changelogOnlineEnglish: 'El modo online ya está disponible en inglés y español.',
  changelogOnlineQueue: 'La lista de equipos rota en cada turno: primero aparece el entrenador actual y después los siguientes.',
  changelogOnlineRooms: 'Acceso a partidas mediante código de sala, opción de abandonar y gestión de salas desde la pantalla del anfitrión.',
  changelogOnlineTeams: 'Los móviles muestran todos los equipos finales. Los entrenadores también muestran su Pokémon favorito.',
  changelogOnlineAnimations: 'Mejoras en la pantalla del anfitrión, elecciones animadas y etiquetas con los motes.',
  changelogFestaShared: 'Tiradas FESTA compartidas, habilidades y resultados de turno sincronizados entre anfitrión y jugadores.',
  changelogFestaChoices: 'El anfitrión muestra la elección de rivales y las opciones FESTA permiten buscar.',
  changelogFestaSkips: 'La probabilidad de carta FESTA se comprueba después de cada encuentro saltado en el modo online.',
  gachaProfile: "Perfil",
  gachaPcSections: "Secciones del PC",
  gachaAudio: "Sonido",
  gachaOpeningSounds: "Sonido de las aperturas",
  gachaOpenProfile: "PC · Perfil",
  gachaProfileUnlockHint: "Completa retos para desbloquear más opciones.",
  gachaEquipProfileHint: "Elige tus recompensas desbloqueadas en PC · Perfil.",
  gachaQuestBoard: "Tablón de entrenadores",
  gachaQuestArchiveHint: "Cada captura cuenta, aunque el Pokémon ya no esté en tu PC.",
  gachaQuestWaterTitle: "Equipo de agua",
  gachaQuestStartersTitle: "El primer trío",
  gachaQuestSpeciesTitle: "La colección crece",
  gachaQuestShinyTitle: "Un brillo especial",
  gachaQuestKantoTitle: "De paseo por Kanto",

  gachaCelebrationFirstShiny: '¡Tu primer variocolor! ¡Sabía que escondía una estrella aquí!',
  gachaCelebrationFive: '¡Cinco Pokémon diferentes! ¡Esta colección empieza a tener buena pinta!',
  gachaCelebrationTwentyFive: '¡Veinticinco! ¡Te has ganado un sitio entre los coleccionistas!',
  gachaNewEntry: "¡Nunca visto!",
  gachaDrawBank: "{count} / 3 tiradas disponibles",
  gachaBankFull: "Tiradas acumuladas al máximo. Abre una para dejar espacio.",
  gachaBankRefill: "Próxima carga en {time} · una cada hora",
  gachaSoundOn: "Sonido activado",
  gachaSoundOff: "Sonido desactivado",
  gachaSearchCollection: "Buscar nombre o número",
  gachaType: "Tipo",
  gachaAllTypes: "Todos los tipos",
  gachaSort: "Ordenar por",
  gachaSortSlot: "Posición en la caja",
  gachaSortNumber: "Número de Pokédex",
  gachaSortName: "Nombre",
  gachaSortRecent: "Más recientes",
  gachaFavorites: "Favoritos primero",
  gachaFavoritesOnly: "Solo favoritos",
  gachaFavorite: "♥ Marcar favorito",
  gachaUnfavorite: "Quitar favorito",
  gachaRenameBox: "Nombre de la caja",
  gachaUndoRelease: "Deshacer liberación (30 s)",
  gachaRestored: "El Pokémon ha vuelto al PC.",
  gachaDragHint: "Arrastra Pokémon entre casillas o a otra caja. En pantallas táctiles, usa Mover.",
  gachaEmptySearch: "No hay Pokémon que coincidan con estos filtros.",
  gachaCollectionSummary: "{count} coleccionados · {shiny} variocolor",
  gachaDexCategory: "Categoría de la colección",
  gachaSpecies: "Especies",
  gachaForms: "Formas",
  gachaAllGenerations: "Todas las generaciones",
  gachaDexStatus: "Estado en la colección",
  gachaAll: "Todos",
  gachaOwned: "Capturado",
  gachaSeen: "Visto",
  gachaMissing: "Sin capturar",
  gachaDiscoverHint: "Revela este Pokémon en una tirada para descubrir su ficha.",
  gachaShinyOwned: "Variocolor registrado",
  gachaCloseDetails: "Cerrar ficha",
  gachaQuests: "Retos de colección",
  gachaQuestsHint: "Completa tu colección para desbloquear decoraciones. Las capturas siguen contando tras liberar un Pokémon.",
  gachaQuestWater: "Captura 5 Pokémon de agua diferentes",
  gachaQuestStarters: "Consigue los tres iniciales de Kanto",
  gachaQuestSpecies: "Captura 25 especies diferentes",
  gachaQuestShiny: "Captura tu primer variocolor",
  gachaQuestKanto: "Completa el 25 % de la Pokédex de Kanto",
  gachaReward: "Recompensa",
  gachaClaimReward: "Recoger recompensa",
  gachaClaimed: "Recogida",
  gachaQuestClaimed: "Desbloqueado: {reward}",
  gachaCustomize: "Personaliza tu rincón",
  gachaCustomizeHint: "Elige una decoración, un fondo de cajas o un título desbloqueado.",
  gachaScene: "Fondo de la página",
  gachaBoxTheme: "Fondo de las cajas",
  gachaTrainerTitle: "Título de entrenador",
  gachaLocked: "Bloqueado",
  gachaSceneDefault: "Fondo original",
  gachaSceneForest: "Rincón del bosque",
  gachaSceneStars: "Cielo estrellado",
  gachaBoxDefault: "Cajas clásicas",
  gachaBoxSunset: "Atardecer",
  gachaTitleTrainer: "Entrenador Pokémon",
  gachaTitleCollector: "Coleccionista de Kanto",
  gachaTitleShiny: "Buscador de Shinies",
  gachaMachineGrowing: "¡Tu colección va creciendo! ¿Listo para otras tres sorpresas?",
  gachaMachineCollector: "Te estás haciendo coleccionista. Déjame ver qué tengo para ti...",
  gachaMachineShiny: "¡Me acuerdo de ese variocolor! ¿Buscamos otro?",
  gachaOpening: "La Poké Ball se está abriendo...",

  onlineTurnPrefix: "Turno de",
  onlineSetupHint: "Crea la sala y comparte el enlace. Cada jugador elige su nombre al entrar; el número de jugadores se decide al empezar.",
  onlineCreate: "Crear sala",
  onlineCreating: "Creando...",
  onlineRoom: "Sala",
  onlineLink: "Enlace",
  onlineDeleteQuestion: "¿Borrar la partida para todos? Se eliminarán la sala y la partida guardada en este dispositivo.",
  onlineDeleting: "Borrando...",
  onlineConfirmDelete: "Sí, borrar partida",
  onlineDelete: "Borrar partida",
  onlineLobby: "Sala de espera · {count} jugadores",
  onlineLobbyHint: "Comparte el enlace y empieza cuando estéis todos. Participarán los jugadores conectados en ese momento.",
  onlineConnected: "Conectado",
  onlineDisconnected: "Desconectado",
  onlineWaitingPlayers: "Esperando jugadores...",
  onlineStarting: "Empezando...",
  onlineStart: "Empezar partida ({count})",
  onlineViewGame: "Consultar partida y crear torneo",
  onlineChoosesFor: "elige el Pokémon para",
  onlineWaitingRival: "Esperando la elección del rival desde su dispositivo.",
  onlineResolveDevice: "El jugador activo resuelve la carta desde su dispositivo.",
  onlineAdvanceDevice: "El jugador avanza al siguiente turno desde su móvil.",
  onlineLeave: "Salir de la partida",
  onlineDeleted: "Partida borrada",
  onlineDeletedHint: "El host ha borrado la sala {code}. Podéis crear otra partida online.",
  onlineHome: "Volver al inicio",
  onlineReconnecting: "Reconectando...",
  onlineRejoin: "Volver a entrar",
  onlineWaitingHost: "Esperando al host...",
  onlineWaitingFor: "Esperando a",
  onlineOtherPlayer: "otro jugador",
  onlineLastEncounter: "Último encuentro: debes quedártelo.",
  onlineFestaItem: "Objeto FESTA",
  onlineFestaAbility: "Habilidad FESTA",
  onlineFestaMove: "Movimiento FESTA",
  onlineChoosePokemon: "Elige un Pokémon",
  onlineSearchItem: "Buscar objeto",
  onlineSearchAbility: "Buscar habilidad",
  onlineSearchMove: "Buscar movimiento",
  onlineSearchHint: "Nombre en español o inglés",
  onlineSearchResults: "Resultados de búsqueda",
  onlineNoResults: "No hay resultados. Prueba con otro nombre.",
  onlineSelection: "Selección:",
  onlineRandomItem: "El objeto se elegirá al azar.",
  onlineReroll: "Elige un pick para rerollear",
  onlineChangeForm: "Elige un Pokémon para cambiar de forma",
  onlineTrade: "Intercambio",
  onlineTradeLast: "Cambia tu último pick",
  onlineRivalPokemon: "Pokémon rival",
  onlineCardError: "No se pudo preparar la carta",
  onlineCardErrorHint: "El servidor no ha enviado una acción para resolverla. Actualiza la partida; si continúa, el organizador debe actualizar el servidor Online.",
  onlineRefreshing: "Actualizando...",
  onlineRefresh: "Actualizar partida",
  onlineRecovering: "Recuperando tu turno",
  onlineNoControls: "No se han recibido las acciones de tu turno.",
  onlineJoinTitle: "Unirse a una partida",
  onlineRollingRival: "Sorteando rival...",
  onlineRivalChosen: "¡Rival elegido!",
  onlineRollingFesta: "Sorteo FESTA...",
  onlineFestaResolved: "¡Carta FESTA resuelta!",
  onlineRolling: "Sorteando...",
  onlineResolvedFor: "ha resuelto la carta para",
  onlineDrawRival: "Rival elegido",
  onlineDrawPokemon: "Pokémon elegido",
  onlineDrawItem: "Objeto sorteado",
  onlineDrawForm: "Forma sorteada",
  onlineTimeout: "No se pudo contactar con el servidor. Espera 1 minuto a que el servidor se despierte, por favor.",
  onlineUnexpectedError: "Error inesperado.",
  onlineLeft: "Has salido de la partida.",

  festaZoroarkName: 'Era un Zoroark!?',
  festaZoroarkDescription: 'Uno de tus Pok\u00e9mon, elegido al azar, se transforma en Zoroark.',
  festaDittoName: 'Era un Ditto!?',
  festaDittoDescription: 'Uno de tus Pok\u00e9mon, elegido al azar, se transforma en Ditto.',
  festaChangeFormName: 'Cambio de Forma',
  festaChangeFormDescription: 'Escoge uno de tus Pok\u00e9mon para que cambie a otra forma disponible al azar.',
  festaRandomChangeFormName: '\u00bfY este qui\u00e9n es?',
  festaRandomChangeFormDescription: 'Un Pok\u00e9mon compatible de cualquier equipo, elegido al azar, cambia a otra forma disponible.',
  openTournament: 'Ver torneo',
  competitionRecommendation: 'Formato recomendado', competitionIdealTitle: '\u00a1Sois un buen n\u00famero para torneo!',
  competitionIdealReason: 'Con {count} jugadores pod\u00e9is hacer eliminaci\u00f3n directa sin byes ni pases gratuitos.',
  competitionByeReason: 'Con {count} jugadores, la eliminaci\u00f3n directa necesitar\u00eda {byes} pases directos.',
  singleElimination: 'Eliminaci\u00f3n directa', swissFormat: 'Sistema suizo', createCompetition: 'Crear torneo',
  createSwiss: 'Crear torneo suizo', useElimination: 'Usar eliminaci\u00f3n directa igualmente',
  swissDescription: 'Todos juegan varias rondas y se enfrentan principalmente a jugadores con resultados similares.',
  eliminationByeNote: 'Algunos jugadores pasar\u00e1n de ronda sin jugar.',
  swissRecommendedRounds: 'Recomendaci\u00f3n: {count} rondas suizas', swissRounds: 'Rondas suizas',
  swissRoundsRange: 'Elige un n\u00famero entero entre 1 y {max}.',
  nearbyTournamentSizes: 'Tama\u00f1os ideales m\u00e1s cercanos para eliminaci\u00f3n directa: {lower} y {upper} jugadores.',
  changeCompetitionFormat: 'Cambiar formato de competici\u00f3n', competitionReplace: 'Crear otro torneo borrar\u00e1 los resultados actuales.',
  swissRoundProgress: 'Ronda {current} de {total}', swissNextRound: 'Emparejar siguiente ronda', swissCompleted: 'Torneo terminado',
  swissBye: 'Bye (+1 punto)', swissRematch: 'Revancha: no era posible emparejar a todos sin repetir rivales.',
  swissStandings: 'Clasificaci\u00f3n', swissPoints: 'Puntos', swissWins: 'Victorias', swissLosses: 'Derrotas', swissByes: 'Byes',
  swissDirect: 'Directo', swissBuchholz: 'Buchholz', swissLottery: 'Sorteo', swissTrainer: 'Entrenador',
  swissScoring: 'Victoria: 1 punto. Derrota: 0. Bye: 1 punto, sin victoria jugada.',
  swissTiebreaks: 'Desempates: enfrentamiento directo (liguilla completa si empata un grupo), despu\u00e9s Buchholz (suma de puntos de los rivales) y sorteo aleatorio guardado. Gana el n\u00famero de sorteo menor.',
  swissUndo: 'Deshacer \u00faltimo resultado o emparejamiento', competitionStartError: 'No se pudo crear la competici\u00f3n. Int\u00e9ntalo de nuevo.',
  tournament: 'Torneo', drawTournament: 'Sortear torneo', redrawTournament: 'Volver a sortear',
  redrawQuestion: '\u00bfVolver a sortear y borrar todos los resultados del torneo?', confirmRedraw: 'Volver a sortear',
  tournamentSummary: '{players} entrenadores / {matches} combates', tournamentProgress: '{done} / {total} combates terminados',
  tournamentBye: 'Pase directo', tournamentWaiting: 'Pendiente de ganador', tournamentFinal: 'Final',
  tournamentSemifinals: 'Semifinales', tournamentQuarterfinals: 'Cuartos de final',
  tournamentChampion: 'Campe\u00f3n', tournamentWinner: 'Marcar a {name} como ganador', tournamentUndo: 'Deshacer \u00faltimo resultado',
  tournamentError: 'No se pudo guardar el torneo. Int\u00e9ntalo de nuevo.', closeTeam: 'Cerrar equipo',
  favoriteQuestion: '\u00bfCu\u00e1l es tu Pok\u00e9mon favorito?', searchPokemon: 'Buscar Pok\u00e9mon',
  changeFavorite: 'Cambiar Pok\u00e9mon favorito', noPokemonFound: 'No se encontraron Pok\u00e9mon',
  favoriteLoadError: 'No se pudieron cargar los Pok\u00e9mon. Inténtalo de nuevo.',
  darkMode: 'Activar modo nocturno', lightMode: 'Activar modo diurno',
  playMonotype: 'Jugar Ten Pick Monotype', monotypeTagline: 'Un tipo. Seis Pokémon.',
  random: 'Aleatorio', playerType: 'Tipo de {name}',
  insufficientPool: 'No hay suficientes familias de Pokémon para estos filtros. Crea un draft con m\u00e1s generaciones u otro tipo.',
  mega: 'Mega', selectGeneration: 'Selecciona al menos una generaci\u00f3n.',
  generations: 'Generaciones', specialForms: 'Formas especiales', gigantamax: 'Gigamax',
  shiny: 'Variocolor',
  home: 'Inicio', language: 'Idioma', chooseGame: 'Elige un juego de Pokefunny',
  tenPickSection: 'Juegos Ten Pick', tenPickHubTagline: 'Modos de draft para montar equipos r\u00e1pido.',
  pokeGachaTagline: 'Abre cápsulas y descubre Pokémon.', playPokeGacha: 'Jugar PokeGacha',
  pokeGachaPending: 'En desarrollo.',
  alreadyRegistered: 'Ya lo tienes registrado en la Pokédex',
  gachaReady: 'Pulsa la máquina para sacar tres Poke Balls.',
  gachaSpinning: 'Girando...',
  gachaPull: 'Pulsar máquina',
  gachaNextDraw: 'Próxima tirada en {time}',
  gachaWaitSorry: '\u00a1Lo siento! Espera a la siguiente hora en punto.',
  gachaWaitToldYou: 'Te he dicho que no puedes.',
  gachaWaitNope: 'Que no.',
  gachaWaitSorryNo: 'Lo siento pero no.',
  gachaAnnoyedOffer: '"Vale, pesado, te voy a dar una Poke Ball, pero te callas, ¿eh?"',
  gachaAnnoyedLastOffer: '"Vale, una última Poke Ball. Ya no más, ¿eh?"',
  gachaAccept: 'Aceptar',
  gachaDecline: 'No aceptar',
  gachaBonusRolling: 'Una Poke Ball ha salido rodando por detrás de la máquina.',
  gachaBonusReady: 'Recoge la Poke Ball.',
  gachaBonusPreparing: 'La Poke Ball secreta está temblando...',
  gachaChooseBonus: 'Elige este Pokémon y envíalo al PC.',
  gachaChoosePokemon: 'Elige un Pokémon',
  gachaRevealPokemon: 'Revelar Pokémon {count}',
  gachaOpenPc: 'Abrir PC',
  gachaOpenPokedex: 'Abrir Pokédex',
  gachaPcPokemon: 'Pokémon del PC',
  gachaPokedex: 'Pokédex',
  gachaClose: 'Cerrar',
  gachaBoxes: 'Cajas',
  gachaBox: 'Caja {count}',
  gachaSlot: 'Casilla {count}',
  gachaNickname: 'Mote',
  gachaMove: 'Mover',
  gachaRelease: 'Liberar',
  gachaSelectPcPokemon: 'Selecciona un Pokémon del PC.',
  gachaGeneration: 'Generación {count}',
  gachaRemaining: 'Faltan {remaining} de {total}',
  gachaUnknownPokemon: 'Pokémon desconocido',
  gachaPreparing: 'La máquina está preparando las cápsulas...',
  gachaRevealAll: 'Pulsa cada Poke Ball para revelar sus Pokémon.',
  gachaLoadError: 'No se pudo cargar la tirada. Prueba otra vez.',
  gachaChooseOne: 'Elige uno de los tres. Ese Pokémon irá al PC.',
  gachaKeepRevealing: 'Sigue revelando las Poke Balls.',
  gachaRevealFirst: 'Primero revela las tres Poke Balls.',
  gachaPcFull: 'El PC está lleno. Libera o mueve algún Pokémon.',
  gachaSavedToPc: '{name} se ha guardado en el PC.',
  gachaChoosePcSlot: 'Elige una casilla del PC para moverlo.',
  gachaReleased: '{name} ha sido liberado. Sigue registrado en la Pokédex.',
  gachaSaveError: 'No se ha podido guardar en este navegador.',
  tagline: 'Diez encuentros. Una elecci\u00f3n.', play: 'Jugar Ten Pick', playFesta: 'Jugar Ten Pick Festa', myDrafts: 'Mis drafts',
  festaTagline: 'Las cartas Festa pueden interrumpir cualquier encuentro.',
  festaChance: 'Probabilidad de carta Festa (%)', festaResolve: 'Resolver carta', festaConfirm: 'Confirmar',
  festaDeck: 'Deck de Cartas',
  festaItem: 'Objeto equipado', festaMove: 'Movimiento', festaAbility: 'Habilidad',
  festaAbilityRivalAnyName: 'Rival sin l\u00edmites: habilidad',
  festaAbilityRivalAnyDescription: 'Elige cualquier habilidad de la lista para un Pok\u00e9mon rival elegido al azar.',
  festaAbilityRandomName: 'Talento sorpresa',
  festaAbilityRandomDescription: 'Elige cualquier habilidad de la lista para un Pok\u00e9mon elegido al azar de cualquier equipo.',
  festaAll: 'Todos', festaRivals: 'Rivales',
  festaInvalidMove: 'Este Pok\u00e9mon no puede aprender ese movimiento.', festaNoTargets: 'Todav\u00eda no hay Pok\u00e9mon disponibles.',
  festaItemRandomRivalName: 'Regalo a un rival aleatorio',
  festaItemRandomRivalDescription: 'Elige un objeto para un Pok\u00e9mon aleatorio de un equipo rival.',
  festaItemRandomAllName: 'Un regalo para... \u00a1\u00bfalguien!?',
  festaItemRandomAllDescription: 'Elige un objeto para un Pok\u00e9mon aleatorio de cualquier equipo, incluido el tuyo.',
  festaItemChosenRivalName: 'Regalo para tu rival',
  festaItemChosenRivalDescription: 'Elige un Pok\u00e9mon de cualquier rival y un objeto para equiparlo.',
  festaItemRandomOwnName: 'Objeto sorpresa',
  festaItemRandomOwnDescription: 'Se sortea un objeto. Elige uno de tus Pok\u00e9mon para equiparlo.',
  festaItemRandomOpponentName: 'Objeto sorpresa para el rival',
  festaItemRandomOpponentDescription: 'Se sortea un objeto. Elige un Pok\u00e9mon rival para equiparlo.',
  festaItemChosenRandomName: 'Entrega aleatoria',
  festaItemChosenRandomDescription: 'Elige un objeto para un Pok\u00e9mon aleatorio de tu equipo.',
  festaItemRandomGroupName: 'Objetos para todos',
  festaItemRandomGroupDescription: 'Se sortea un objeto. Elige un Pok\u00e9mon rival para equiparlo.',
  festaMoveRivalAnyName: 'Rival sin l\u00edmites',
  festaMoveRivalAnyDescription: 'Escribe cualquier movimiento para un Pok\u00e9mon rival elegido al azar.',
  festaMoveRandomName: 'Entrenamiento sorpresa',
  festaMoveRandomDescription: 'Escribe un movimiento para un Pok\u00e9mon aleatorio de cualquier equipo.',
  festaReroll: 'Repetir tirada', festaReplaced: 'Sustituye a {name}',
  festaChoosingRival: 'Eligiendo rival',
  festaRivalSelected: 'Tu rival es',
  festaChoosingTarget: 'Eligiendo Pok\u00e9mon',
  festaTargetSelected: 'El regalo va para',
  festaRivalChoosesFor: '{rival} elige por {player}',
  festaFirstPokemon: 'Primer Pokémon', festaSecondPokemon: 'Segundo Pokémon', festaYourLastPick: 'Tu \u00faltima elecci\u00f3n',
  festaCardFirstStageName: 'Pokémon de primera fase',
  festaCardFirstStageDescription: 'Elige un Pokémon que sea la primera fase de una línea evolutiva. Se une directamente a tu equipo.',
  festaCardMinorLegendaryName: 'Legendario o mítico',
  festaCardMinorLegendaryDescription: 'Elige un Pokémon legendario o mítico. Se une directamente a tu equipo.',
  festaCardOpponentFullyEvolvedName: 'Rival: Pok\u00e9mon completamente evolucionado',
  festaCardOpponentFullyEvolvedDescription: 'Un rival aleatorio elige un Pok\u00e9mon completamente evolucionado para ti. Se une directamente a tu equipo.',
  festaCardOpponentFirstStageName: 'Rival: Pokémon de primera fase',
  festaCardOpponentFirstStageDescription: 'Un rival aleatorio elige un Pokémon de primera fase para ti. Se une directamente a tu equipo.',
  festaCardOpponentMinorLegendaryName: 'Rival: legendario o mítico',
  festaCardOpponentMinorLegendaryDescription: 'Un rival aleatorio elige un Pokémon legendario o mítico para ti. Se une directamente a tu equipo.',
  festaCardForcedRerollName: 'Repetición obligatoria',
  festaCardForcedRerollDescription: 'Reemplaza uno de tus Pokémon anteriores por uno nuevo generado con las reglas normales.',
  festaCardTradeAnyName: 'Intercambio total',
  festaCardTradeAnyDescription: 'Intercambia dos Pokémon elegidos por dos jugadores cualesquiera.',
  festaCardTradeLastName: 'Intercambia tu \u00faltima elecci\u00f3n',
  festaCardTradeLastDescription: 'Intercambia el último Pokémon que hayas recibido por un Pokémon de otro jugador.',
  playOnline: 'Jugar Online',
  joinGameHint: 'Introduce el código de una sala para unirte a una partida online.',
  joinGameButton: 'Entrar en la partida',
  joinRoomCode: 'Código de la sala',
  joinCodeHint: 'El código de 6 caracteres que comparte el host.',
  joinPlayerName: 'Nombre',
  joiningGame: 'Entrando...',
  newDraft: 'Nuevo draft', noDrafts: 'No hay drafts guardados', completed: 'Terminado', inProgress: 'En curso',
  pokemonPicked: 'Pokémon elegidos', deleteQuestion: '\u00bfBorrar este draft?', delete: 'Borrar', cancel: 'Cancelar',
  viewTeams: 'Ver equipos', continue: 'Continuar', deleteDraft: 'Borrar draft', deleteDraftFor: 'Borrar draft de {name}',
  trainerName: 'Nombre del entrenador', add: 'A\u00f1adir', remove: 'Quitar', removePlayer: 'Quitar a {name}',
  draftNicknamesRequired: 'Motes obligatorios', draftNickname: 'Mote',
  teamSize: 'Pokémon por equipo', start: 'Empezar draft', draftComplete: 'Draft terminado', finalTeams: 'Equipos finales',
  player: 'Jugador', loading: 'Buscando Pokémon...', turnError: 'No se pudo preparar el turno. Inténtalo de nuevo.',
  retry: 'Reintentar', turnOf: 'Turno de {name}', lastEncounter: '\u00daltimo encuentro', lastChoice: 'Es tu \u00faltima opci\u00f3n',
  pick: 'Elegir', skip: 'Pasar', remaining: '{count} encuentros restantes', teams: 'Equipos',
  draftOrder: 'Orden de turno', round: 'Ronda {count}', pickedBy: '{name} ha elegido', encounter: 'Encuentro',
  picked: 'Elegido', skipped: 'Descartado', undiscovered: 'Sin descubrir', finalTeamsButton: 'Ver equipos finales',
  nextTurn: 'Siguiente turno', preparePaste: 'Preparar Pokepaste', preparePasteFor: 'Preparar Pokepaste de {name}',
  abilitiesLoading: 'Consultando habilidades...', viewPaste: 'Ver Pokepaste', teamOf: 'Equipo de {name}',
  closePaste: 'Cerrar Pokepaste', closePasteFor: 'Cerrar Pokepaste de {name}', copyTeam: 'Copiar equipo',
  copied: 'Copiado', copy: 'Copiar', teamAbilitiesLoading: 'Consultando habilidades del equipo de {name}',
  pasteError: 'No se pudo preparar el equipo. Inténtalo de nuevo.',
  copyError: 'No se pudo copiar. Puedes seleccionar el texto del equipo.',
  unknownForm: 'No se reconoce la forma de {name} en Showdown.',
  unknownAbility: 'No se pudo obtener la habilidad de {name}.',
};

const onlineServerMessages: Record<string, string> = {
  "Sesión de host inválida.": "Invalid host session.",
  "La partida ya ha empezado.": "The game has already started.",
  "La partida ya está iniciada.": "The game has already started.",
  "Nombre inválido.": "Invalid name.",
  "Sesión de jugador inválida.": "Invalid player session.",
  "La partida ya ha empezado y no participas en ella.": "The game has already started and you are not a participant.",
  "El host no puede realizar acciones de jugador.": "The host cannot perform player actions.",
  "Sala inexistente.": "Room not found.",
  "Solo el host puede gestionar la partida.": "Only the host can manage the game.",
  "No hay jugadores conectados en la sala.": "There are no connected players in the room.",
  "Hay una carta FESTA pendiente.": "A FESTA card is pending.",
  "Esta acción ya fue procesada.": "This action has already been processed.",
  "Ese Pokémon no pertenece a las opciones actuales.": "That Pokémon is not one of the current options.",
  "El último Pokémon es obligatorio.": "You must keep the last Pokémon.",
  "No hay carta FESTA activa.": "There is no active FESTA card.",
  "Carta FESTA inválida.": "Invalid FESTA card.",
  "No puedes resolver este cambio de forma.": "You cannot resolve this form change.",
  "Ese Pokémon no pertenece a tu equipo.": "That Pokémon is not on your team.",
  "No puedes resolver este modificador FESTA.": "You cannot resolve this FESTA modifier.",
  "No hay un objetivo válido para esta carta.": "There is no valid target for this card.",
  "Elige un valor válido para esta carta.": "Choose a valid value for this card.",
  "No puedes resolver esta carta FESTA.": "You cannot resolve this FESTA card.",
  "Ese Pokémon no es una opción válida.": "That Pokémon is not a valid option.",
  "No puedes hacer este reroll.": "You cannot reroll this pick.",
  "Ese pick no existe.": "That pick does not exist.",
  "No puedes resolver este intercambio.": "You cannot resolve this trade.",
  "La carta FESTA activa no permite intercambios.": "The active FESTA card does not allow trades.",
  "Debes elegir un Pokémon de otro jugador.": "Choose a Pokémon from another player.",
  "Elige dos Pokémon distintos.": "Choose two different Pokémon.",
  "El intercambio ya no es válido.": "The trade is no longer valid.",
  "No puedes avanzar este turno.": "You cannot advance this turn.",
  "Ese Pokémon ya no existe.": "That Pokémon no longer exists.",
  "Ese Pokémon no tiene otra forma disponible.": "That Pokémon has no other available form.",
  "No hay suficientes Pokémon para preparar el turno.": "There are not enough Pokémon to prepare the turn.",
  "La partida no ha empezado.": "The game has not started.",
  "No es tu turno.": "It is not your turn.",
  "No hay opción activa.": "There is no active option.",
  "Introduce un mote para este Pokémon.": "Enter a nickname for this Pokémon.",
  "Selección inválida.": "Invalid selection.",
  "Espera a que termine la animación FESTA.": "Wait for the FESTA animation to finish.",
};

const spanishTypes: Record<string, string> = {
  normal: 'Normal', fire: 'Fuego', water: 'Agua', grass: 'Planta', electric: 'El\u00e9ctrico',
  ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno', ground: 'Tierra', flying: 'Volador',
  psychic: 'Ps\u00edquico', bug: 'Bicho', rock: 'Roca', ghost: 'Fantasma', dragon: 'Drag\u00f3n',
  dark: 'Siniestro', steel: 'Acero', fairy: 'Hada',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  readonly language = signal<Language>(this.readLanguage());

  constructor() {
    this.document.documentElement.lang = this.language();
  }

  setLanguage(language: Language): void {
    this.language.set(language);
    this.document.documentElement.lang = language;
    try { localStorage.setItem('pokefunny.language', language); } catch { /* Keep the session choice when storage is unavailable. */ }
  }

  t(key: TranslationKey, values: Record<string, string | number> = {}): string {
    const message = this.language() === 'es' ? es[key] : en[key];
    return message.replace(/\{(\w+)\}/g, (match, name: string) => String(values[name] ?? match));
  }

  onlineError(message: string): string {
    for (const key of ['onlineTimeout', 'onlineUnexpectedError', 'onlineLeft'] as const) {
      if (message === es[key] || message === en[key]) return this.t(key);
    }
    return this.language() === 'en' ? onlineServerMessages[message] ?? message : message;
  }

  typeName(type: string): string {
    return this.language() === 'es' ? spanishTypes[type.toLowerCase()] ?? type : type;
  }

  date(value: string): string {
    return new Intl.DateTimeFormat(this.language() === 'en' ? 'en-GB' : 'es-ES', {
      day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit',
    }).format(new Date(value));
  }

  private readLanguage(): Language {
    try { return localStorage.getItem('pokefunny.language') === 'es' ? 'es' : 'en'; }
    catch { return 'en'; }
  }
}
