import { DOCUMENT } from '@angular/common';
import { Injectable, inject, signal } from '@angular/core';

const en = {
  favoriteQuestion: 'What is your favorite Pokemon?', searchPokemon: 'Search Pokemon',
  changeFavorite: 'Change favorite Pokemon', noPokemonFound: 'No Pokemon found',
  favoriteLoadError: 'Could not load the Pokemon. Please try again.',
  darkMode: 'Enable night mode', lightMode: 'Enable day mode',
  playMonotype: 'Play Ten Pick Monotype', monotypeTagline: 'One type. Six Pokemon.',
  random: 'Random', playerType: 'Type for {name}',
  insufficientPool: 'Not enough eligible Pokemon families for these filters. Create a draft with more generations or a different type.',
  mega: 'Mega', selectGeneration: 'Select at least one generation.',
  shiny: 'Shiny',
  home: 'Home', language: 'Language', chooseGame: 'Choose a Pokefunny game',
  tenPickSection: 'Ten Pick games', tenPickHubTagline: 'Draft modes for quick team building.',
  pokeGachaTagline: 'Open capsules and discover Pokemon.', playPokeGacha: 'Play PokeGacha',
  pokeGachaPending: 'Work in. Progress.',
  alreadyRegistered: 'Already registered in your Pokedex',
  gachaReady: 'Press the machine to draw three Poke Balls.',
  gachaSpinning: 'Spinning...',
  gachaPull: 'Press machine',
  gachaNextDraw: 'Next draw in {time}',
  gachaWaitSorry: 'Sorry! Wait until the next hour o\'clock.',
  gachaWaitToldYou: 'I told you that you cannot.',
  gachaWaitNope: 'Nope.',
  gachaWaitSorryNo: 'Sorry, but no.',
  gachaAnnoyedOffer: '"Fine, pest, I will give you a Poke Ball, but be quiet, okay?"',
  gachaAccept: 'Accept',
  gachaDecline: 'Decline',
  gachaBonusRolling: 'A Poke Ball rolled out from behind the machine.',
  gachaBonusReady: 'Pick up the Poke Ball.',
  gachaBonusPreparing: 'The hidden Poke Ball is shaking...',
  gachaChooseBonus: 'Choose this Pokemon and send it to the PC.',
  gachaChoosePokemon: 'Choose a Pokemon',
  gachaRevealPokemon: 'Reveal Pokemon {count}',
  gachaOpenPc: 'Open PC',
  gachaOpenPokedex: 'Open Pokedex',
  gachaPcPokemon: 'PC Pokemon',
  gachaPokedex: 'Pokedex',
  gachaClose: 'Close',
  gachaBoxes: 'Boxes',
  gachaBox: 'Box {count}',
  gachaSlot: 'Slot {count}',
  gachaNickname: 'Nickname',
  gachaMove: 'Move',
  gachaRelease: 'Release',
  gachaSelectPcPokemon: 'Select a Pokemon from the PC.',
  gachaGeneration: 'Generation {count}',
  gachaRemaining: '{remaining} left out of {total}',
  gachaUnknownPokemon: 'Unknown Pokemon',
  gachaPreparing: 'The machine is preparing the capsules...',
  gachaRevealAll: 'Press each Poke Ball to reveal its Pokemon.',
  gachaLoadError: 'Could not load this draw. Try again.',
  gachaChooseOne: 'Choose one of the three. That Pokemon will go to the PC.',
  gachaKeepRevealing: 'Keep revealing the Poke Balls.',
  gachaRevealFirst: 'Reveal all three Poke Balls first.',
  gachaPcFull: 'The PC is full. Release or move a Pokemon.',
  gachaSavedToPc: '{name} was saved to the PC.',
  gachaChoosePcSlot: 'Choose a PC slot to move it.',
  gachaReleased: '{name} was released. It stays registered in the Pokedex.',
  gachaSaveError: 'Could not save in this browser.',
  tagline: 'Ten encounters. One choice.', play: 'Play Ten Pick', playFesta: 'Play Ten Pick Festa', myDrafts: 'My drafts',
  festaChance: 'Festa Card chance (%)', festaResolve: 'Resolve card', festaConfirm: 'Confirm',
  festaReroll: 'Reroll', festaReplaced: 'Replaces {name}',
  festaChoosingRival: 'Choosing rival',
  festaRivalSelected: 'Your rival is',
  festaRivalChoosesFor: '{rival} chooses for {player}',
  festaFirstPokemon: 'First Pokemon', festaSecondPokemon: 'Second Pokemon', festaYourLastPick: 'Your last pick',
  festaCardFirstStageName: 'First-stage Pokemon',
  festaCardFirstStageDescription: 'Choose a Pokemon that is the first stage of an evolutionary line. It joins your team directly.',
  festaCardMinorLegendaryName: 'Legendary or Mythical',
  festaCardMinorLegendaryDescription: 'Choose a Legendary or Mythical Pokemon. It joins your team directly.',
  festaCardOpponentFullyEvolvedName: 'Rival Fully Evolved',
  festaCardOpponentFullyEvolvedDescription: 'A random rival chooses a fully evolved Pokemon for you. It joins your team directly.',
  festaCardOpponentFirstStageName: 'Rival First-stage Pokemon',
  festaCardOpponentFirstStageDescription: 'A random rival chooses a first-stage Pokemon for you. It joins your team directly.',
  festaCardOpponentMinorLegendaryName: 'Rival Legendary or Mythical',
  festaCardOpponentMinorLegendaryDescription: 'A random rival chooses a Legendary or Mythical Pokemon for you. It joins your team directly.',
  festaCardForcedRerollName: 'Forced Reroll',
  festaCardForcedRerollDescription: 'Replace one of your previous picks with a new Pokemon generated under the normal rules.',
  festaCardTradeAnyName: 'Full Trade',
  festaCardTradeAnyDescription: 'Trade two Pokemon chosen by any two players.',
  festaCardTradeLastName: 'Trade Your Last Pick',
  festaCardTradeLastDescription: 'Swap your most recent Pokemon for another player\'s Pokemon.',
  newDraft: 'New draft', noDrafts: 'No saved drafts', completed: 'Completed', inProgress: 'In progress',
  pokemonPicked: 'Pokemon picked', deleteQuestion: 'Delete this draft?', delete: 'Delete', cancel: 'Cancel',
  viewTeams: 'View teams', continue: 'Continue', deleteDraft: 'Delete draft', deleteDraftFor: 'Delete draft for {name}',
  trainerName: 'Trainer name', add: 'Add', remove: 'Remove', removePlayer: 'Remove {name}',
  teamSize: 'Pokemon per team', start: 'Start draft', draftComplete: 'Draft complete', finalTeams: 'Final teams',
  player: 'Player', loading: 'Finding Pokemon...', turnError: 'Could not prepare this turn. Please try again.',
  retry: 'Retry', turnOf: "{name}'s turn", lastEncounter: 'Final encounter', lastChoice: 'This is your last choice',
  pick: 'Pick', skip: 'Skip', remaining: '{count} encounters remaining', teams: 'Teams',
  draftOrder: 'Draft order', round: 'Round {count}', pickedBy: '{name} picked', encounter: 'Encounter',
  picked: 'Picked', skipped: 'Skipped', undiscovered: 'Undiscovered', finalTeamsButton: 'View final teams',
  nextTurn: 'Next turn', preparePaste: 'Prepare Pokepaste', preparePasteFor: 'Prepare Pokepaste for {name}',
  abilitiesLoading: 'Looking up abilities...', viewPaste: 'View Pokepaste', teamOf: "{name}'s team",
  closePaste: 'Close Pokepaste', closePasteFor: 'Close Pokepaste for {name}', copyTeam: 'Copy team',
  copied: 'Copied', copy: 'Copy', teamAbilitiesLoading: 'Looking up abilities for {name}',
  pasteError: 'Could not prepare the team. Please try again.',
  copyError: 'Could not copy. You can select the team text instead.',
  unknownForm: 'The form of {name} is not recognized by Showdown.',
  unknownAbility: 'Could not find the ability for {name}.',
} as const;

export type TranslationKey = keyof typeof en;
export type Language = 'en' | 'es';

const es: Record<TranslationKey, string> = {
  favoriteQuestion: '\u00bfCu\u00e1l es tu Pok\u00e9mon favorito?', searchPokemon: 'Buscar Pok\u00e9mon',
  changeFavorite: 'Cambiar Pok\u00e9mon favorito', noPokemonFound: 'No se encontraron Pok\u00e9mon',
  favoriteLoadError: 'No se pudieron cargar los Pok\u00e9mon. Inténtalo de nuevo.',
  darkMode: 'Activar modo nocturno', lightMode: 'Activar modo diurno',
  playMonotype: 'Jugar Ten Pick Monotype', monotypeTagline: 'Un tipo. Seis Pokémon.',
  random: 'Aleatorio', playerType: 'Tipo de {name}',
  insufficientPool: 'No hay suficientes familias de Pokémon para estos filtros. Crea un draft con m\u00e1s generaciones u otro tipo.',
  mega: 'Mega', selectGeneration: 'Selecciona al menos una generaci\u00f3n.',
  shiny: 'Variocolor',
  home: 'Inicio', language: 'Idioma', chooseGame: 'Elige un juego de Pokefunny',
  tenPickSection: 'Juegos Ten Pick', tenPickHubTagline: 'Modos de draft para montar equipos r\u00e1pido.',
  pokeGachaTagline: 'Abre cápsulas y descubre Pokémon.', playPokeGacha: 'Jugar PokeGacha',
  pokeGachaPending: 'Work in. Progress.',
  alreadyRegistered: 'Ya lo tienes registrado en la Pokédex',
  gachaReady: 'Pulsa la máquina para sacar tres Poke Balls.',
  gachaSpinning: 'Girando...',
  gachaPull: 'Pulsar máquina',
  gachaNextDraw: 'Próxima tirada en {time}',
  gachaWaitSorry: '\u00a1Lo siento! Espera a la siguiente hora en punto.',
  gachaWaitToldYou: 'Te he dicho que no puedes.',
  gachaWaitNope: 'Nope.',
  gachaWaitSorryNo: 'Lo siento pero no.',
  gachaAnnoyedOffer: '"Vale, pesado, te voy a dar una Poke Ball, pero te callas, ¿eh?"',
  gachaAccept: 'Aceptar',
  gachaDecline: 'No aceptar',
  gachaBonusRolling: 'Una Poke Ball ha salido rodando por detrás de la máquina.',
  gachaBonusReady: 'Recoge la Poke Ball.',
  gachaBonusPreparing: 'La Poke Ball secreta está temblando...',
  gachaChooseBonus: 'Elige este Pokémon y envíalo al PC.',
  gachaChoosePokemon: 'Elige un Pokémon',
  gachaRevealPokemon: 'Revelar Pokémon {count}',
  gachaOpenPc: 'Abrir PC',
  gachaOpenPokedex: 'Abrir Pokédex',
  gachaPcPokemon: 'Pokémon del PC',
  gachaPokedex: 'Pokédex',
  gachaClose: 'Cerrar',
  gachaBoxes: 'Cajas',
  gachaBox: 'Caja {count}',
  gachaSlot: 'Casilla {count}',
  gachaNickname: 'Mote',
  gachaMove: 'Mover',
  gachaRelease: 'Liberar',
  gachaSelectPcPokemon: 'Selecciona un Pokémon del PC.',
  gachaGeneration: 'Generación {count}',
  gachaRemaining: 'Faltan {remaining} de {total}',
  gachaUnknownPokemon: 'Pokémon desconocido',
  gachaPreparing: 'La máquina está preparando las cápsulas...',
  gachaRevealAll: 'Pulsa cada Poke Ball para revelar sus Pokémon.',
  gachaLoadError: 'No se pudo cargar la tirada. Prueba otra vez.',
  gachaChooseOne: 'Elige uno de los tres. Ese Pokémon irá al PC.',
  gachaKeepRevealing: 'Sigue revelando las Poke Balls.',
  gachaRevealFirst: 'Primero revela las tres Poke Balls.',
  gachaPcFull: 'El PC está lleno. Libera o mueve algún Pokémon.',
  gachaSavedToPc: '{name} se ha guardado en el PC.',
  gachaChoosePcSlot: 'Elige una casilla del PC para moverlo.',
  gachaReleased: '{name} ha sido liberado. Sigue registrado en la Pokédex.',
  gachaSaveError: 'No se ha podido guardar en este navegador.',
  tagline: 'Diez encuentros. Una elecci\u00f3n.', play: 'Jugar Ten Pick', playFesta: 'Jugar Ten Pick Festa', myDrafts: 'Mis drafts',
  festaChance: 'Probabilidad de carta Festa (%)', festaResolve: 'Resolver carta', festaConfirm: 'Confirmar',
  festaReroll: 'Repetir tirada', festaReplaced: 'Sustituye a {name}',
  festaChoosingRival: 'Eligiendo rival',
  festaRivalSelected: 'Tu rival es',
  festaRivalChoosesFor: '{rival} elige por {player}',
  festaFirstPokemon: 'Primer Pokémon', festaSecondPokemon: 'Segundo Pokémon', festaYourLastPick: 'Tu último pick',
  festaCardFirstStageName: 'Pokémon de primera fase',
  festaCardFirstStageDescription: 'Elige un Pokémon que sea la primera fase de una línea evolutiva. Se une directamente a tu equipo.',
  festaCardMinorLegendaryName: 'Legendario o mítico',
  festaCardMinorLegendaryDescription: 'Elige un Pokémon legendario o mítico. Se une directamente a tu equipo.',
  festaCardOpponentFullyEvolvedName: 'Rival: Pokémon fully evolved',
  festaCardOpponentFullyEvolvedDescription: 'Un rival aleatorio elige un Pokémon fully evolved para ti. Se une directamente a tu equipo.',
  festaCardOpponentFirstStageName: 'Rival: Pokémon de primera fase',
  festaCardOpponentFirstStageDescription: 'Un rival aleatorio elige un Pokémon de primera fase para ti. Se une directamente a tu equipo.',
  festaCardOpponentMinorLegendaryName: 'Rival: legendario o mítico',
  festaCardOpponentMinorLegendaryDescription: 'Un rival aleatorio elige un Pokémon legendario o mítico para ti. Se une directamente a tu equipo.',
  festaCardForcedRerollName: 'Repetición obligatoria',
  festaCardForcedRerollDescription: 'Reemplaza uno de tus Pokémon anteriores por uno nuevo generado con las reglas normales.',
  festaCardTradeAnyName: 'Intercambio total',
  festaCardTradeAnyDescription: 'Intercambia dos Pokémon elegidos por dos jugadores cualesquiera.',
  festaCardTradeLastName: 'Intercambia tu último pick',
  festaCardTradeLastDescription: 'Intercambia el último Pokémon que hayas recibido por un Pokémon de otro jugador.',
  newDraft: 'Nuevo draft', noDrafts: 'No hay drafts guardados', completed: 'Terminado', inProgress: 'En curso',
  pokemonPicked: 'Pokémon elegidos', deleteQuestion: '\u00bfBorrar este draft?', delete: 'Borrar', cancel: 'Cancelar',
  viewTeams: 'Ver equipos', continue: 'Continuar', deleteDraft: 'Borrar draft', deleteDraftFor: 'Borrar draft de {name}',
  trainerName: 'Nombre del entrenador', add: 'A\u00f1adir', remove: 'Quitar', removePlayer: 'Quitar a {name}',
  teamSize: 'Pokémon por equipo', start: 'Empezar draft', draftComplete: 'Draft terminado', finalTeams: 'Equipos finales',
  player: 'Jugador', loading: 'Buscando Pokémon...', turnError: 'No se pudo preparar el turno. Inténtalo de nuevo.',
  retry: 'Reintentar', turnOf: 'Turno de {name}', lastEncounter: '\u00daltimo encuentro', lastChoice: 'Es tu \u00faltima opci\u00f3n',
  pick: 'Elegir', skip: 'Pasar', remaining: '{count} encuentros restantes', teams: 'Equipos',
  draftOrder: 'Orden de turno', round: 'Ronda {count}', pickedBy: '{name} ha elegido', encounter: 'Encuentro',
  picked: 'Elegido', skipped: 'Descartado', undiscovered: 'Sin descubrir', finalTeamsButton: 'Ver equipos finales',
  nextTurn: 'Siguiente turno', preparePaste: 'Preparar Pokepaste', preparePasteFor: 'Preparar Pokepaste de {name}',
  abilitiesLoading: 'Consultando habilidades...', viewPaste: 'Ver Pokepaste', teamOf: 'Equipo de {name}',
  closePaste: 'Cerrar Pokepaste', closePasteFor: 'Cerrar Pokepaste de {name}', copyTeam: 'Copiar equipo',
  copied: 'Copiado', copy: 'Copiar', teamAbilitiesLoading: 'Consultando habilidades del equipo de {name}',
  pasteError: 'No se pudo preparar el equipo. Inténtalo de nuevo.',
  copyError: 'No se pudo copiar. Puedes seleccionar el texto del equipo.',
  unknownForm: 'No se reconoce la forma de {name} en Showdown.',
  unknownAbility: 'No se pudo obtener la habilidad de {name}.',
};

const spanishTypes: Record<string, string> = {
  normal: 'Normal', fire: 'Fuego', water: 'Agua', grass: 'Planta', electric: 'El\u00e9ctrico',
  ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno', ground: 'Tierra', flying: 'Volador',
  psychic: 'Ps\u00edquico', bug: 'Bicho', rock: 'Roca', ghost: 'Fantasma', dragon: 'Drag\u00f3n',
  dark: 'Siniestro', steel: 'Acero', fairy: 'Hada',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  readonly language = signal<Language>(this.readLanguage());

  constructor() {
    this.document.documentElement.lang = this.language();
  }

  setLanguage(language: Language): void {
    this.language.set(language);
    this.document.documentElement.lang = language;
    try { localStorage.setItem('pokefunny.language', language); } catch { /* Keep the session choice when storage is unavailable. */ }
  }

  t(key: TranslationKey, values: Record<string, string | number> = {}): string {
    const message = this.language() === 'es' ? es[key] : en[key];
    return message.replace(/\{(\w+)\}/g, (match, name: string) => String(values[name] ?? match));
  }

  typeName(type: string): string {
    return this.language() === 'es' ? spanishTypes[type.toLowerCase()] ?? type : type;
  }

  date(value: string): string {
    return new Intl.DateTimeFormat(this.language() === 'en' ? 'en-GB' : 'es-ES', {
      day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit',
    }).format(new Date(value));
  }

  private readLanguage(): Language {
    try { return localStorage.getItem('pokefunny.language') === 'es' ? 'es' : 'en'; }
    catch { return 'en'; }
  }
}
